/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BookList: typeof import('./src/components/bookList.vue')['default']
    EnterView: typeof import('./src/components/basic/enterView.vue')['default']
    MyAgreementModal: typeof import('./src/components/my-agreement-modal.vue')['default']
    MyIdUploader: typeof import('./src/components/my-id-uploader.vue')['default']
    MyInput: typeof import('./src/components/my-input.vue')['default']
    MyLogo: typeof import('./src/components/my-logo.vue')['default']
    MyModal: typeof import('./src/components/my-modal.vue')['default']
    MyNavigator: typeof import('./src/components/my-navigator.vue')['default']
    MySelectCell: typeof import('./src/components/my-select-cell.vue')['default']
    MySmsBtn: typeof import('./src/components/my-sms-btn.vue')['default']
    MyTag: typeof import('./src/components/my-tag.vue')['default']
    MyTitle: typeof import('./src/components/my-title.vue')['default']
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCalendar: typeof import('@nutui/nutui-taro')['Calendar']
    NutCascader: typeof import('@nutui/nutui-taro')['Cascader']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCellGroup: typeof import('@nutui/nutui-taro')['CellGroup']
    NutCheckbox: typeof import('@nutui/nutui-taro')['Checkbox']
    NutCountdown: typeof import('@nutui/nutui-taro')['Countdown']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutImagePreview: typeof import('@nutui/nutui-taro')['ImagePreview']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutNavbar: typeof import('@nutui/nutui-taro')['Navbar']
    NutPicker: typeof import('@nutui/nutui-taro')['Picker']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutRadio: typeof import('@nutui/nutui-taro')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui-taro')['RadioGroup']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutStep: typeof import('@nutui/nutui-taro')['Step']
    NutSteps: typeof import('@nutui/nutui-taro')['Steps']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTextarea: typeof import('@nutui/nutui-taro')['Textarea']
    NutUploader: typeof import('@nutui/nutui-taro')['Uploader']
  }
}
