/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BookList: typeof import('./src/components/bookList.vue')['default']
    EnterView: typeof import('./src/components/basic/enterView.vue')['default']
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutNavbar: typeof import('@nutui/nutui-taro')['Navbar']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    Welcome: typeof import('./src/components/welcome.vue')['default']
  }
}
