/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BookList: typeof import('./src/components/bookList.vue')['default']
    EnterView: typeof import('./src/components/basic/enterView.vue')['default']
    MyIdUploader: typeof import('./src/components/my-id-uploader.vue')['default']
    MyInput: typeof import('./src/components/my-input.vue')['default']
    MyLogo: typeof import('./src/components/my-logo.vue')['default']
    MyNavigator: typeof import('./src/components/my-navigator.vue')['default']
    MySmsBtn: typeof import('./src/components/my-sms-btn.vue')['default']
    MyTag: typeof import('./src/components/my-tag.vue')['default']
    MyTitle: typeof import('./src/components/my-title.vue')['default']
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutNavbar: typeof import('@nutui/nutui-taro')['Navbar']
    NutRadio: typeof import('@nutui/nutui-taro')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui-taro')['RadioGroup']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
  }
}
